### ISSUE TITLE
Count with Increments

### ISSUE THREAD

**Issue by P-Pan089** [muratali016/Yolov7-Object-Counter#1]
Hello Murat,

great Repo. I have a question. I want to count the total amount of classes that were detected and increment the number and not just count the amount that is currently seen. So it should only increase.
I want to do this on my Jetson Nano and would appreciate your help.

**Comment by muratali016** [comment]
Hello @P-Pan089 I'm working on it tomorrow I'm gonna share with you the solution

**Comment by P-Pan089** [comment]
Hello @muratali016,

that would be really great. Thank you!

**Comment by muratali016** [comment]
Can you please try again with this code https://github.com/muratali016/Yolov7-Object-Counter/blob/main/detect_and_count_total.py @P-Pan089

**Comment by P-Pan089** [comment]
Hello @muratali016,
when i try it, it still only counts the amount that is currently seen. It's not much different.
Don't we need a tracker for this type of counting?
Still thank you!

**Comment by muratali016** [comment]
I made another counter in another project exactly the same as you mentioned but there was a condition (cars had to cross to line) to count objects please  take a look at here: https://github.com/muratali016/Yolov7-License-Plate-Recognition-Program
Maybe from this code, you can find a solution. There is a big problem here that there is a for loop in the part in detect.py where we take the detected objects @P-Pan089

**Comment by muratali016** [comment]
Yes tracker will definitely work
