### ISSUE TITLE
How to run TRACK SOURCE.py

### ISSUE THREAD

**Issue by AT9991** [muratali016/Yolov7-Object-Counter#2]
Hi there,

Great repo! How to run TRACK SOURCE.py? I clone the yolov7 file and copied the TRACK SOURCE.py file. when I run it gives the following error:

Traceback (most recent call last):
  File "track_source.py", line 31, in <module>
    from yolov7.models.experimental import attempt_load
ModuleNotFoundError: No module named 'yolov7'

Please help me to debug it.

**Comment by muratali016** [comment]
@AT9991 Hi thanks. You can use that Colab file to run track: https://colab.research.google.com/drive/1RK1IgQx6Fr7D2BwgCQJiUiZPclj69Myv?usp=sharing

please don't forget that you have to change track.py file with these codes here https://drive.google.com/file/d/1ZZvsDL4up29cVjt2hcOKwi795o07PULM/view?usp=sharing

**Comment by AT9991** [comment]
@muratali016 Hi thanks for the instructions. I followed the steps, but getting this error. Please check. Thank you

/content/Yolov7_StrongSORT_OSNet/strong_sort/deep/reid/torchreid/metrics/rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(
Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
IDetect.fuse
Model: osnet_x0_25
- params: 203,568
- flops: 82,316,000
Successfully loaded pretrained weights from "/content/Yolov7_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
(1, 256, 128, 3)
video 1/1 (1/494) /content/Dec27_TestVideo.mp4: Traceback (most recent call last):
  File "track.py", line 374, in <module>
    main(opt)
  File "track.py", line 369, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 150, in run
    for frame_idx, (path, im, im0s, vid_cap) in enumerate(dataset):
  File "/content/Yolov7_StrongSORT_OSNet/yolov7/utils/datasets.py", line 189, in __next__
    img = letterbox(img0, self.img_size, stride=self.stride)[0]
  File "/content/Yolov7_StrongSORT_OSNet/yolov7/utils/datasets.py", line 998, in letterbox
    dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by muratali016** [comment]
You have to use cuda which is GPU in your local or in your notebook otherwise you must change some lines as the error says
